# Generated by Django 5.1 on 2024-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
