# Generated by Django 5.1 on 2024-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfviewer', '0002_pdffile_delete_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
